HTTP_GET_REQUEST = 1
HTTP_HEAD_REQUEST = 2
HTTP_OPTIONS_REQUEST = 3
HTTP_PUT_REQUEST = 4 
HTTP_DELETE_REQUEST = 5
HTTP_POST_REQUEST = 6
HTTP_PATCH_REQUEST = 7

HTTP_AUTH_METHOD_BASIC = 0
HTTP_AUTH_METHOD_DIGEST = 1
HTTP_AUTH_METHOD_NTLM = 2
HTTP_AUTH_METHOD_BEARER = 3